# Generated by Django 3.1.1 on 2020-10-13 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Select language', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.book'),
        ),
    ]
